name: "Create the documentation"

on: pull_request

jobs:
  create_doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.40.2
          cache: true
      - run : pixi run doc
